name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Test Action-Solution
        uses: poojapatidar21/Test-Action-Solution@Test-V1
        with: 
            who-to-greet: "Pooja"
            
      - name: Test Action-Solution
        uses: poojapatidar21/Test-Action-Solution@Test-V1
        with: 

            ConnectedServiceName: "Maven"

      - name: Test password
        run:
          echo $PASS_SECRET
        env:
          PASS_SECRET: ${{ secrets.PASSWORD_SECRET }}

      - name: Print azure credentials
        run:
          echo $AZURE_SECRET
        env:
          AZURE_SECRET: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Secrets
        uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "keyvault-2-basic"
          secrets: 'PASSWORD-SECRET'
        